### ISSUE TITLE
Default empty value

### ISSUE THREAD

**Issue by amorphius** [facebook/immutable-js#532] opened 2015-07-03 16:31 UTC
I have suggestion to add default empty immutable object when reading value from any ImmutableJS object, so user don't have to think that return value could be undefined and write null check every time or add default value as second parameter. I use `get` or `getIn` a lot in my project and it's annoying to add default parameter in each `get` call. You could name it `read`, `readIn` or something

**Comment by amorphius** [comment] 2015-07-03 16:34
It's useful when reading some list from immutable structure and you want to apply method like `map` or `reduce`

```
// this could throw an exception
state.getIn(['path', 'to', 'the', 'list']).map((x) => x + 1)
```

**Comment by leebyron** [comment] 2015-07-14 04:36
Could you expand on what code you wish you could type which today does not yet exist? I think I understand the request, but am not entirely sure how you are hoping for it to be exposed.

**Comment by amorphius** [comment] 2015-07-14 15:27
```
var obj = immutable.Map({
  prop1: {
    prop11: 11,
    prop12: [0, 1, 2, 3, 4, 5, 6]
  }
});

var mapped = obj.getIn(['prop1', 'props12']).map(function(n) { return n +1; });
var screwed = obj.getIn(['prop1', 'props13']).map(function(n) { return n +1; });
```

Last line will throw an error, since `undefined.map is not a function`. I want some another method, e.g. `read`, `readIn`, so I can do this

```
var empty = obj.readIn(['prop1', 'props13']).map(function(n) { return n +1; });
```
Which is equivalent of
```
var empty = obj.getIn(['prop1', 'props13'], immutable.Map()).map(function(n) { return n +1; });
```

It's useful only for collection when chaining few methods like `filter`, `map`, `reduce` in one line. And it becomes tedious to specify default collection in each method.

The only problem I think, that we do not store only collections in properties, so sometimes it could be number and string and `undefined` or `null` is OK. In this case it's better to use `getIn` instead of `readIn`.

**Comment by Dashed** [comment] 2015-07-15 12:31
I share similar sentiments. But I feel like this shouldn't go into core. If extendable Immutable types is possible, then we can have a custom operation that would partially apply `getIn`/`get`: https://github.com/facebook/immutable-js/issues/301

**Comment by dubrowgn** [comment] 2016-08-02 15:33
I think this is a bigger issue than most people give it credit for. It's not uncommon for an undefined collection and an empty collection to be treated logically the same. Not just coercing undefined into an empty collection, but being able to test if a collection is either undefined or empty. Combine this with the fact that javascript eagerly evaluates function parameters, and passing in a new default collection is a poor solution too because you are continually creating new collections whether you use them or not.

**Comment by niksajanjic** [comment] 2016-11-30 16:57
I will just point out certain problems I have, but I'm not saying these are issues of Immutable, just pointing them out. As a frontend developer I can't always influence what should response from API look like. For instance, Sequalize (Node framework) by default sets empty object properties to _null_ which causes problems to Immutable's get function. For example, let's take this object as an example:

    const profile = {
      bio: null,
      confirmed: true,
      createdAt: '2016-11-24T15:32:51.695Z',
      email: 'test@email.com',
      firstname: null,
      id: 1,
      lastname: null,
      resourceId: null,
      updatedAt: '2016-11-24T15:32:51.695Z',
    }

I'm also using React to render my views. So, everytime I have to do this ternary operator inside my JSX to know if this property exist before I render it or I should render empty string:

    profile.get('bio') ? profile.get('bio') : ''

I can't use _.has_ function because key really does exist and it will return true and I also can't use this:

    profile.get('bio', '')

Because it will return null back, which does sound like correct behavior, although it's not going in my favor. The key shouldn't exist or it should be set to undefined for _get_ function to work correctly in my case. Unfortunately, with this responses (when I can't influence API responses) I'm either forced to remove every null key on every response before storing object in state or write ternary operators everywhere in JSX.

Lastly, even in cases where I influence API and key really doesn't exist it can be tiresome to write second parameter on _get_ function to always be empty string which is what creator if this issue already reported.

**Comment by leebyron** [comment] 2017-03-07 23:09
Closing this aging issue. I think this is just a fact of life in a JS environment unfortunately, at least until we get something like the [null-coalescing operator](https://en.wikipedia.org/wiki/Null_coalescing_operator) is added to the language.

For what it's worth, I use `.get('thing') || backupVal` pattern all the time myself.

**Closed by leebyron** 2017-03-07 23:09 UTC
