### ISSUE TITLE
Record({0: 'test'}) in Safari 9.1.1 somehow affecting global Regexp object

### ISSUE THREAD

**Issue by alunyov** [facebook/immutable-js#924] opened 2016-07-14 19:54 UTC
### What happened

It's really strange thing. And I'm not sure where and how to fix that.
So - I'm using Immutable.js (3.8.1) and Angular (1.5.7). And when I create something link this:

``` js
angular.module('test', [])
.controller('TestCtrl', function($scope, $window, dateFilter) {
  var Record = $window.Immutable.Record;
  var Test = Record({0: 'Test'});
  $scope.today = dateFilter(new Date());
  var m = $window.Immutable.Map({0: 1});
  // Comment next line to fix the issue
  var t = new Test();
  $scope.todayEmpty = dateFilter(new Date());
  $scope.t = t;
}).run();
angular.bootstrap(document, ['test']);
```

angular's `dateFilter` starts returning empty strings on valid Date objects.
I've figured out that this code

``` js
// angular.js dateFilter
while (format) {
  match = DATE_FORMATS_SPLIT.exec(format);
  // match = _.cloneDeep(match); --> this is helps
  // but otherwise match is not array (or something)
  if (match) {
    parts = concat(parts, match, 1); // here it starts to return array with empty values 
    format = parts.pop();
  } else {
    parts.push(format);
    format = null;
  }
}
```

is broken after  `var t = new Test()`
And I can reproduce it only in Safari.

Here is the some examples:
Safari version: http://take.ms/tXQHy
Plunkr: https://plnkr.co/edit/5d3tclj8KFe5KnyB3aqe?p=preview

**Comment by andrew-makarenko** [comment] 2016-07-14 20:02
reproduced! really weird behavior

**Comment by leebyron** [comment] 2017-03-04 00:57
W.T.F.

Could you please open an issue on Safari? https://webkit.org/reporting-bugs/

This sounds like a serious issue on their end.

**Comment by leebyron** [comment] 2017-10-04 22:33
I'm going to close this issue since more recent versions of Safari have come out, and there's not much this library seems to be able to do to work around it.

If anyone encounters this bug again, or has updates from a webkit bug, please report it.

**Closed by leebyron** 2017-10-04 22:33 UTC
Labels: bug, help wanted, wontfix
