### ISSUE TITLE
[BUG?] deleteIn removes the values but not the key

### ISSUE THREAD

**Issue by zomars** [facebook/immutable-js#1607] opened 2018-09-20 20:14 UTC
### What happened

Using deleteIn in a normalized Map removes the values inside the key but doesn't remove the key itself.

### How to reproduce

Using this:

```js
state.deleteIn(['entities', 'services', '20']);
```

returns this:

![image](https://user-images.githubusercontent.com/3504472/45844253-1c1a1380-bcdf-11e8-8270-f30b96139ca5.png)

**Comment by AyWa** [comment] 2018-09-24 04:28
Hey,

Do you have an example to reproduce ?

I tried something like:

```
const { Map, fromJS } = require('immutable');

const map1 = {catalogues: fromJS({entities: {services: {20: {id: "something", dx: "else"}}}})}
const map2 = {catalogues: Map({ entities: Map({services: Map({20: Map({ id: "something", dx: "else"})})})})}

const result1 = map1.catalogues.deleteIn(["entities", "services", "20"])
const result2 = map2.catalogues.deleteIn(["entities", "services", "20"])

console.log(result1.getIn(["entities", "services"]))
console.log(result2.getIn(["entities", "services"]))
```
And results is:
```
Map {}
Map {}
```

So seems like the key `20` is correctly deleted (tried with immutable `3.8.2` and `v4.0.0-rc.10`)

**Comment by leebyron** [comment] 2018-10-30 22:20
I also can't reproduce this. Closing, but feel free to reopen with a failing test case!

**Closed by leebyron** 2018-10-30 22:20 UTC
