### ISSUE TITLE
Extending/creating custom Immutable types

### ISSUE THREAD

**Issue by tgriesser** [facebook/immutable-js#301] opened 2015-01-30 20:48 UTC
I figured a separate ticket would be a better place to discuss what an API for this feature might look like, since the potential implementation approach depends on this heavily. So here are some things I've been thinking about. While the syntax:

```js
class User extends Immutable.Map {
}
```

is kind of neat/simple and initially looks idiomatic ES6, it comes with a lot of baggage. First, it's always necessary to define a custom constructor to pass along the return value from the `super` call as this isn't done implicitly in js classes. 

```js
class User extends Immutable.Map {
   constructor(val) {
      return super(val)
   }
}
```

Further, as the constructor doesn't really act like a normal constructor there end up being a lot of additional checks necessary to ensure that another Map passed into the custom type is [coerced correctly](https://github.com/tgriesser/immutable-js/blob/10deaf40f829bd81dc7a58afe861bbe9d518cb18/src/Map.js#L34).

So I'm wondering whether there should be something more like:

```js
var User = Immutable.make(Immutable.Map, {
   
   fullName() {
     return this.get('firstName') + ' ' + this.get('lastName')
   }

})
```

would be better suited. It would allow for having a dedicated constructor type for a custom immutable type. It might still come with a perf-hit but it would be better isolated from the core implementation.

Also, it might be worth examining at what the equivalent would have looked like in [mori](https://github.com/swannodette/mori/pull/108) when implemented with cljs protocols.

**Comment by janmarek** [comment] 2015-02-12 07:49
@tgriesser are there any problems with extending Map or List (except the return super in constructor)? Can I extend them safely now?

**Comment by tgriesser** [comment] 2015-02-12 15:35
No  - it's not possible currently unless you use [my fork](https://github.com/facebook/immutable-js/pull/227) - which I know has its own minor issues depending on the type and isn't well tested. Might be better to wait and see if there's something more official.

**Comment by vkurchatkin** [comment] 2015-02-18 11:26
+1

**Comment by tgriesser** [comment] 2015-03-04 03:32
I've gotten pretty far on this lately, I've been working on a [version](https://github.com/tgriesser/immutable-js/commit/d17e00595677c50f28e1a374d4ab5e917ac9f4a4) which has the entire suite passing, maintains factory functionality (`instanceof` checks on types) while still allowing for extending into custom types and with a 50-100% perf improvement over master on `npm run perf`.

@leebyron would love to catch up on IRC sometime about some questions/ ideas I have for v4 based on some of these findings. Mainly around the less-common api surface area (Seq / Collection / Iterables) organization and guarantees. Also around some of the "Clowntown" stuff in declassify.

I think there's some huge room for improvements while keeping stuff true to the JavaScript-y ideals for Immutable.

**Comment by dandelany** [comment] 2015-03-04 22:04
Just wanted to +1 this as well... I'm working on an Immutable Graph class and running into these problems.

@tgriesser to clarify your "it's not possible currently" comments above - are you saying it's not possible at all currently to write a class which extends Immutable.Map? I tried your syntax from above:

```
class User extends Immutable.Map {
   constructor(val) {
      return super(val)
   }
}
```

However, in this case it seems `new User() instanceOf User == false`

**Comment by tgriesser** [comment] 2015-03-04 22:09
Yes, my I'm saying it's not possible at all... the syntax above works on my [other fork](https://github.com/facebook/immutable-js/pull/227).

The Immutable classes are not actually implemented as classes but factory functions (intentionally so you don't need to call them with `new`), but this ends up being terribly inefficient performance wise, which is where the 50-100% perf gains I've seen in my latest attempts at this are coming from.

So it'll eventually be possible but I don't really want to spend any significant time on it past what I already have until I get a chance to talk to @leebyron a bit more.

**Comment by leebyron** [comment] 2015-03-04 23:07
I'm excited to see more of what you've built, Tim! Mind writing it up for me in an email or something? lee@leebyron.com

**Comment by janmarek** [comment] 2015-03-05 02:11
@tgriesser @leebyron thank you for your work guys

**Comment by facebook-github-bot-6** [comment] 2015-08-04 18:04
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by Anahkiasen** [comment] 2015-08-09 19:25
Would love to be able to extend the core types

**Comment by alexeisavca** [comment] 2015-08-24 04:21
Works for me with Webpack and babel loader.
```
import {Map} from "immutable";
class MyMap extends Map{
  setStuff(val){
    return this.set('stuff', val);
  }
}

console.log(new MyMap().setStuff('derp').toJS());//{stuff: 'derp'}
```

**Comment by aglemann** [comment] 2015-09-15 15:34
+1

**Comment by kainoa21** [comment] 2015-09-15 20:15
+1

**Comment by alexandrecolas** [comment] 2015-09-23 11:11
+1

**Comment by lucasjans** [comment] 2015-09-29 07:24
+1

**Comment by adbl** [comment] 2015-10-12 09:27
+1

**Comment by AndrX** [comment] 2015-10-16 01:17
+1

**Comment by zloylos** [comment] 2015-10-30 09:00
+1

**Comment by jadbox** [comment] 2015-11-09 00:06
+1 
@dandelany I would also love to see an Immutable Graph lib!

**Comment by maxbates** [comment] 2015-11-11 21:03
+1 this would be enormously helpful. Is there any established way for creating immutables with class methods?

**Comment by leebyron** [comment] 2015-11-11 21:07
I'm still very concerned about the performance implications as well as creating an API that leads to anti patterns. 

For those +1ing, could you please add a use case you're trying to enable that's not currently possible by using Immutable.Record or the existing List and Map structures?

**Comment by tgriesser** [comment] 2015-11-11 21:14
Yeah I'm actually no longer using this fork myself, fully agree with the concern about anti-patterns.

**Comment by jadbox** [comment] 2015-11-11 22:02
@leebyron I just need an Immutable graph interface. Something like: ```state.getIn(['users', 'bob']).edge('likes').map( contentObj => state.setIn(['content', contentObj, 'isLiked'], true));```
```state.getIn(['content', 'firefly']).edge('likedBy').map( user => state.setIn(['users', user, 'foo'], 'bar') );```

I'm tempted to write my own library, but I was hoping to use Immutable as a base. Would it would be better for me to open source something that has the same interface as Immutable, and uses Im under the hood for graph operations?

**Comment by leebyron** [comment] 2015-11-11 23:25
I think that should be entirely possible by composing Immutable.js collections rather than extending them. You can check out OrderedMap as an example of this. It is a new kind of collection with new properties and some differing API, but is implemented by using List and Map

**Comment by flyon** [comment] 2015-11-28 02:49
+1. 

@leebyron as for a useCase. I am building an app with a pretty complex datastructure. Totally possible with native Immutable collections, but some things will be 4 or 5 levels deep.

For example, users can vote multiple times on a voteSlide in a certain presentation, to get a single vote could look like:

    var specificVote = state.getIn([presentationId,slideNumber,participantId,answerId]);

The problem with this is that when there will be other developers working this code later, they will need to know the order of indices / the structure of the app. Ofcourse comments and state inspection will do the job, but what I was thinking about is to create a Presentation which extends Map, which holds Slides which extend Map, which hold Participants, etc ... This way I can make extra methods like:

    var presentation = state.get(presentationId);
    var specificVote = presentation.getSlide(slideNumber).getParticipant(participantId).getVote(voteId);

more code, perhaps less performant(?), but much easier to work with for them, with code completion.

**Comment by callumlocke** [comment] 2015-12-14 13:19
This has been tagged needs-decision for over 9 months. Can we get a decision?

**Comment by DevSide** [comment] 2016-02-09 13:05
+1

**Comment by polkovnikov-ph** [comment] 2016-02-25 10:14
+1

**Comment by disjukr** [comment] 2016-02-29 05:11
+1

**Comment by mitkaaa** [comment] 2016-04-22 13:34
+1

**Comment by wshager** [comment] 2016-05-01 12:30
+1

**Comment by wshager** [comment] 2016-05-01 12:31
I'd like to have a simple way of overriding List.toString()

**Comment by leebyron** [comment] 2016-05-01 18:07
I'm going to officially close this issue since we decided a while back that it wasn't worth the serious performance costs. We would rather have performant data structures rather than subclassable ones. 

This also encourages using plain functions for extended behavior, or composition for more advanced data structures, which are good patterns to follow

**Closed by leebyron** 2016-05-01 18:07 UTC
Labels: needs-decision

**Comment by janmarek** [comment] 2016-05-02 13:49
@leebyron thank you for this update

do you think it would be possible to document everything we need to do properly to make custom data structures using composition?

**Comment by leebyron** [comment] 2016-05-02 13:50
Yes, that's a great idea. In the meantime, check out the source for OrderedMap and OrderedSet, both are "new" data structures built by composing List and Map

**Comment by jdfreder** [comment] 2016-05-18 22:20
For future readers, I created a little package that more or less is an "inheritable" Immutable.Map type https://github.com/jdfreder/inheritable-map

**Comment by philpl** [comment] 2016-08-01 23:11
For anyone who's still interested in this, I wrote an `extendable-immutable` package, similar to @jdfreder's one, but with complete expected behavior: it can be extended multiple times deep, it doesn't break the prototype chain at all (f.e. Map.isMap and x instanceof Map would pass), it doesn't break mutable operations etc.

https://github.com/philpl/extendable-immutable
