### ISSUE TITLE
toMap should take a mapping function

### ISSUE THREAD

**Issue by Daniel15** [facebook/immutable-js#600] opened 2015-08-25 01:04 UTC
It would be nice if `toMap` accepted a mapping function to specify what the values should be:

```
var input = Immutable.List(['a', 's', 'd', 'f']);
var output = input.toMap(x => x.toUpperCase() + '!'); 
// output = Map { 'a': 'A!', 's': 'S!', 'd': 'D!', 'f': 'F!' }
```

You could do `input.toMap().map(x => x.toUpperCase() + '!')` at the moment but it's not as nice :stuck_out_tongue_winking_eye: 

.NET LINQ has similar functionality, except it uses the function to specify the key rather than the value: https://msdn.microsoft.com/en-us/library/bb549277(v=vs.95).aspx

**Comment by ddaza** [comment] 2015-08-25 19:06
The current functionality is done by design, per the documentation of `toMap()`: 

`Note: This is equivalent to Map(this.toKeyedSeq()), but provided for convenience and to allow for chained expressions.`

So the chaining that you're doing is exactly how they meant it to work, I think :smile:.

**Comment by ChrisMarinos** [comment] 2015-09-10 19:41
Note, the code you have would actually produce:

`"Map { 0: "A!", 1: "S!", 2: "D!", 3: "F!" }"` instead of ` Map { 'a': 'A!', 's': 'S!', 'd': 'D!', 'f': 'F!' }`

I'd like a value selector as mentioned above, but I'd actually much prefer a key selector. I find that the lack of a key selector is a much more significant limitation.

**Comment by dubrowgn** [comment] 2016-02-15 19:03
I posted some code for this on #697. Thoughts?

**Comment by leebyron** [comment] 2017-03-08 06:33
Closing this aging issue.

Trying to shy away from `toMap` and family, I'd prefer not to complicate them further.

**Closed by leebyron** 2017-03-08 06:33 UTC
