### ISSUE TITLE
Angular 2 + ImmutableJS causes lot of rerenders

### ISSUE THREAD

**Issue by paramsingh88** [facebook/immutable-js#1042] opened 2017-01-16 17:12 UTC
Printing out log in ngOnChanges of a component having inputs bound with @select immutables. It prints out a lot of times even when the app is idle.
<img width="755" alt="screen shot 2017-01-16 at 10 36 48 pm" src="https://cloud.githubusercontent.com/assets/19772006/21992577/fdd685fe-dc3c-11e6-85f2-07412961e5ec.png">

**Comment by jmalonzo** [comment] 2017-01-16 22:44
I don't think this is an issue with immutable-js, rather with the way your app is using angular.

**Comment by leebyron** [comment] 2017-03-01 04:30
Closing this issue since there's isn't actionable information here. If you can provide a reproducible issue, then please feel free to reopen the issue.

**Closed by leebyron** 2017-03-01 04:30 UTC
