### ISSUE TITLE
TypeScript compiler unable to find immutable.js iterators in for of loop

### ISSUE THREAD

**Issue by xaviergonz** [facebook/immutable-js#1199] opened 2017-04-02 10:58 UTC
Note that this applies to all collections, not only maps.

**Code**
```
import {Map} from "immutable";

const m = Map({ a: 1 });

for (const [key, value] of m) {
    console.log(key, value);
}
```
**Actual**
```
TSError: ⨯ Unable to compile TypeScript
src/test.ts (6,28): Type must have a '[Symbol.iterator]()' method that returns an iterator. (2488)
```

**Reason**
The type definition file for immutable.js doesn't include something like this (I'm not sure where would be the right place to put it though)
```
interface Map<K, V> {
  [Symbol.iterator](): IterableIterator<[K,V]>;
}
```

PS: Typescript 2.2.2, options are (tsconfig.json)
```
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016",
      "dom",
      "dom.iterable",
      "es2017.object"
    ],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "alwaysStrict": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "React",
    "noEmitOnError": false,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "sourceMap": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "strictNullChecks": true,
    "declaration": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false
  }
}
```

**Comment by MrMosterd** [comment] 2017-04-04 18:12
Check #1183

**Comment by kozlitinaelja** [comment] 2017-05-31 23:55
Thank you for reporting @xaviergonz! Closing it since it is a duplicate of #1183

**Closed by kozlitinaelja** 2017-05-31 23:55 UTC
