### ISSUE TITLE
fromJS is not correctly converting nested objects.

### ISSUE THREAD

**Issue by jaitaiwan** [facebook/immutable-js#737] opened 2015-12-31 03:21 UTC
When converting a redux example state:
```js
const state = {
  issues: [{title:"hello"}, {title:"nothing"}]
}
```

is converted to `List [ [object Object], [object Object] ]` instead of `List [ Map {title: "hello"}, Map {title:"nothing"} ]`

From what I understand, fromJS should convert it to the latter version as they are vanilla objects?

**Comment by dchest** [comment] 2016-01-02 00:12
I can't reproduce this from console on the home page in Chrome.

<img width="536" alt="screen shot 2016-01-02 at 01 11 55" src="https://cloud.githubusercontent.com/assets/52677/12072697/db94c878-b0ed-11e5-9218-968e19c70487.png">

**Comment by leebyron** [comment] 2016-01-05 22:40
Closing this since there is an answer with clear code, but please reopen with more details of the issue at hand if your code is different and you've encountered a bug.

**Closed by leebyron** 2016-01-05 22:40 UTC

**Comment by jaitaiwan** [comment] 2016-01-06 00:28
Ok yeh I can't replicate that in the cmd line.
