### ISSUE TITLE
website: logo doesn't overflow in Firefox

### ISSUE THREAD

**Issue by tomByrer** [facebook/immutable-js#847] opened 2016-04-18 18:23 UTC
Hero looks as intended in Chrome, not Fx:
![fb-immutable-firefox](https://cloud.githubusercontent.com/assets/1308419/14614871/566d9518-0560-11e6-9d97-1e0295aabd10.jpg)

**Comment by leebyron** [comment] 2016-04-18 21:25
I can't reproduce this in my Firefox browser - can you share more details about OS/Browser versions?

**Comment by leebyron** [comment] 2017-03-07 07:10
Closing this aging issue - feel free to reopen if still having troubles

**Closed by leebyron** 2017-03-07 07:10 UTC
