### ISSUE TITLE
Using Immutable.js’s Maps with TypeScript

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/immutable-js#683] opened 2015-10-29 09:13 UTC
I'm using immutable.js with TypeScript. I want a typed immutable object, e.g. an object called `Person` with an interface of: `(name: string, age: number)`. 

Ideally I could construct a `Person` and it will be an instance of `Immutable.Map`:

``` js
interface Person {
    name: string;
    age: number
}

var person = Person({ name: 'bob', age: 5 })
person.name // => 'bob'
var newPerson = person.set('name', 'harry');
person.name // => 'bob'
newPerson.name // => 'harry'
```

Is this possible? Sorry if my terminology is not entirely clear!

Thanks :smile:

**Comment by rosendi** [comment] 2015-11-02 12:36
Duplicate of #166 and #341.

**Comment by OliverJAsh** [comment] 2015-11-02 20:16
I'm currently following advice from https://github.com/facebook/immutable-js/issues/341#issuecomment-147940378 but this involves overwriting the type definitions. I would also prefer a way to do this without requiring defaults to be set—ideally TypeScript should throw an error if you tried to create an object missing a property.

**Comment by rosendi** [comment] 2015-11-02 21:00
To be honest I spent a few days now and few months ago trying to find a solution that would fit all the points including a record inheritance with custom methods, attributes checking and properties accessing with a dot-notation, but I still haven't found it. This feature mixed with a record generic type definitions you mentioned above could solve most of them Microsoft/TypeScript#2225. But there is no progress. @leebyron Could you help us?

**Comment by OliverJAsh** [comment] 2016-04-16 20:44
One suggestion is to use Immutable’s Records, but in this case I don't want to allow default values.

**Comment by emirotin** [comment] 2016-06-28 18:53
@OliverJAsh if records work for you setting `undefined` defaults should be effectively the same as not setting them at all. Am I wrong?

**Comment by OliverJAsh** [comment] 2016-06-28 18:55
Yes, correct, it's just boilerplate really.

**Comment by aalpgiray** [comment] 2016-09-07 07:52
I found a class to get prop name as string array, then implemented a SetValue Method this has some rough edges.

`
export class NavigableObject<T>{
    constructor(private obj: T, private path: string[] = []) { }

    To<R>(p: (x: T) => R): NavigableObject<R> {

        let propName = this.getPropName(p)

        if (propName) {
            return new NavigableObject<R>(
                p(this.obj),
                this.path.concat(propName)
            );
        } else {
            return new NavigableObject<R>(
                p(this.obj),
                this.path
            );
        }
    }

    getPath() {
        return this.path;
    }


    private static propertyRegEx = /\.([^\.;]+);?\s*\}$/;

    private getPropName(propertyFunction: Function) {
        let value = NavigableObject.propertyRegEx.exec(propertyFunction.toString())
        if (value)
            return value[1];
    }
}
`

`
 function NavigatableRecordCreator(defaultValues: { [key: string]: any; }, name?: string) {
    abstract class NavigatableRecord<P extends NavigatableRecord<P>> extends Record(defaultValues, name) {
        SetValue<T>(fn: (x: NavigableObject<P>) => NavigableObject<T>, value: T, state: P) {
            return this.setIn(fn(new NavigableObject<P>(state)).getPath(), value)
        }
    }
    return NavigatableRecord;
}

export class IUSER extends NavigatableRecordCreator({
    Name: "",
    Age: 0
})<IUSER> {
    Name: string;
    Age: number;
    SetValue<T>(fn: (x: NavigableObject<IUSER>) => NavigableObject<T>, value: T) {
        return super.SetValue(fn, value, this)
    }
}
`

and then use it like 

`
state.SetValue(t => t.To(q => q.Name), "test string") // typecheks
state.SetValue(t => t.To(q => q.Name), 123) // error
`

it also works with nested properties 

`
somenestedImmutable.(t =>t.To(q => q.Date).To(q => q.Time), 213213123)
`

**Comment by born2net** [comment] 2017-01-23 05:12
Hi Guys,
its 2017, so can we Type a Map now with immutablejs and TypeScript? Specifically enforce the keys.
Posted here: http://stackoverflow.com/questions/41798302/how-do-you-type-an-immutablejs-map-keys
but no one seems to know, odd :/

regards


Sean
================
Checkout the Ultimate Angular 2 Boorstrap App: @ http://ng2.javascriptninja.io
Source@ https://github.com/born2net/ng2Boilerplate

**Comment by leebyron** [comment] 2017-03-08 06:35
Fixed in master, will be released soon

**Closed by leebyron** 2017-03-08 06:35 UTC

**Comment by born2net** [comment] 2017-03-08 18:02
looking fwd to it...
what release will it land on?

**Comment by born2net** [comment] 2017-05-04 19:58
was this released already?

**Comment by born2net** [comment] 2017-05-04 20:10
fyi I tried both of these with latest release immuatble beta rc4 and no luck
```
let state: Map<any, ITimelineState> = Map({
        zoom: 1,
        duration: 500,
        channels: [],
        outputs: [],
        items: []
    });
```

**Comment by jacek213** [comment] 2017-05-16 10:17
@leebyron Can we see any example of usage?

**Comment by born2net** [comment] 2017-05-16 13:19
ya same... really need an example please

**Comment by xugao** [comment] 2017-05-16 22:00
Is this released? An example would be great!

**Comment by born2net** [comment] 2017-05-26 18:22
any news on this?

**Comment by agaurav** [comment] 2017-06-06 15:08
@leebyron can you please post the commits related to fix?

**Comment by DonikaV** [comment] 2017-07-06 13:55
Hello from july 6

**Comment by born2net** [comment] 2017-07-24 20:05
Hello from July 26th

**Comment by born2net** [comment] 2017-07-24 20:07
@leebyron any news on this? would love to be able to Type Maps

**Comment by odiseo42** [comment] 2017-10-10 23:28
@leebyron Hello from October 2017! an example would be much appreciated :)

**Comment by born2net** [comment] 2017-10-10 23:35
same!

**Comment by leebyron** [comment] 2017-10-11 23:52
You may want to look to the TypeScript documentation for examples of how to use TypeScript.

Map is defined in terms of the type of the keys it contains and the type of the values it contains, respectively. It appears as: `Map<KeyType, ValueType>` in TypeScript.

For example, if you wanted a Map with string keys and number values, you'd write `Map<string, number>`. For the example above `Map<any, ITimelineState>`, this implies a Map that will accept any value as a key, and instances of `ITimelineState` as values.

For cases where the type of value at each key will be different depending on the key, then `Map` is likely the wrong choice. Maps are intended for homogeneous collections. For heterogeneous collections with a fixed known set of keys, `Record` is a better fit.

You can see examples of using Record in the Immutable.js documentation here: http://facebook.github.io/immutable-js/docs/#/Record

**Comment by odiseo42** [comment] 2017-10-25 19:47
An example usage for those wondering (following this [post](https://masimplo.com/adding-type-safety-to-immutable-js-with-typescript-string-literals-and-keyof/)), where you want to type check every property accesed via `get`:

```
interface IProduct {
  price: number;
  description: string;
}
```

What you do is first to declare a typing interface for your `Product` as it were a Plan Old JavaScript object. Then you proceed to "wrap" it extending `Immutable.Map`:

```
interface IImmutableProduct extends Immutable.Map<string, any> {
   toJS(): IProduct;
   get<K extends keyof IProduct>(key: K): IProduct[K];
}
```

Thus you'll have type checking over the getter functions of `Product`, in this case `.get('price')` and `.get('description').

**Comment by born2net** [comment] 2017-10-25 20:07
That's great, can't wait to test it

**Comment by aalpgiray** [comment] 2017-10-28 08:23
@odiseo42 so thats all than; great.

`interface IProduct {
    price: number;
    description: string;
}

interface IImmutable<T> extends Map<string,any>{
    toJS():T;
    get<K extends keyof T>(key: K) : T[K];
    set<K extends keyof T>(key: K, value: T[K]): IImmutable<T>;
}



const product : IImmutable<IProduct> = Map({
    price: 0,
    description : "test"
});`

**Comment by Saul-Mirone** [comment] 2018-04-13 10:07
Hi there, I make some attempt and get a solution **with out any** like this:
```typescript
interface ImMap<T, K, V> extends Map<K, V> {
  toJS(): T;
  get<I extends keyof T>(key: I & K): T[I] & V;
  set<S>(o: S): Map<K, V>;
}
//test
interface StringMap {
  [propName: string]: string;
}
type ImStringMap = ImMap<D.StringMap, string, string>;

interface Attach {
  val: string;
  type: number;
  sh1?: string;
  keyName?: string;
}
type ImAttach = ImMap<D.Attach, string, string | number>;
```
It works well for me.

**Comment by bohdanbirdie** [comment] 2018-07-20 05:59
@odiseo42 @Saul-Mirone thanks for the examples!
Any proposals for `getIn` method?

**Comment by born2net** [comment] 2018-07-29 05:57
seems to work:

```

interface IMAPTScannerTabSelection extends Map<string, any> {
    toJS(): IScannerTabSelection;
    get<K extends keyof IScannerTabSelection>(key: K): IScannerTabSelection[K];
}



const scannerTabSelection = {
    mainTab: {
        value: EnumScannerMainTab.MAINTAB_BLOCKS
    },
    switchTab: {
        value: EnumScannerSwitchTab.SWITCH_BROWSE_BLOCKS22
    }
};

var a:IMAPTScannerTabSelection = Map(scannerTabSelection);
var b = a.get("switchTab")
console.log(b);
```

**Comment by mmakrzem** [comment] 2018-10-15 20:34
Can anyone help answer this question: https://stackoverflow.com/questions/52824312/how-to-use-immutablejs-map-with-typescript

I can't figure out how to define my ImmutableMap in TypeScript that contains a List of (child) ImmutableMaps.

**Comment by kushalmahajan** [comment] 2020-04-09 18:47
@odiseo42 What if I need to access the full object. Any workaround for that?

**Comment by JustFly1984** [comment] 2020-04-09 23:51
@kushalmahajan this project more dead than alive, try immer instead

**Comment by kushalmahajan** [comment] 2020-04-10 05:09
@JustFly1984 Thanks for the suggestion but I cannot just try new package. Already deep into it.

**Comment by JustFly1984** [comment] 2020-04-10 05:37
Well, I was deep in immutable.js with 5 projects,until we had to refactor all the projects to typescript, it happened that there is no support :/ we had to refactor anyway, and used immer as 100% typescript support. Also this library is unmaintained for way too long and there is some bugs which killing all the benefits. For example if you have a list of strings more than 32 items, it will iterate without an order :/

**Comment by DonikaV** [comment] 2020-04-30 19:05
Guys in 2020 and with ES6 you don't need immutable, IMHO :)

**Comment by JustFly1984** [comment] 2020-04-30 21:36
@DonikaV 
We need some kind of data structures with persistence properties, cos immutability is not enough fir performance optimized algorithms.

Immutability by itself can be provided with Object.freeze() recursively or shallow. Or simply use immer. But persistance by itself provides huge performance boost

**Comment by ambertide** [comment] 2021-08-04 06:45
This seems to be the most active issue on the regard despite being closed, in my opinion there should be a way to do the following:

```typescript
import { Map } from "immutable";

interface ExampleInterface {
  exampleVariable: string;
  anotherVarible: number;
}

const ourImmutableObject = new Map<ExampleInterface>();
```

Allowing this would drastically simplify typescript support for the end user.
