### ISSUE TITLE
Sub-cursor updates are concurrent

### ISSUE THREAD

**Issue by jameshopkins** [facebook/immutable-js#618] opened 2015-09-09 12:10 UTC
``` js
const data = Immutable.fromJS({a: 1, b: 2});

const cursor = Cursor.from(data, newData => {
  console.log(newData)
});

cursor.set('a', 2); // Map {"a": 2, "b": 2}
cursor.set('b', 3); // Map {"a": 1, "b": 3}
```

The second `.set()` call disregards the value which the first `.set()` call sets. I require the second `.set()` to return `Map {"a": 2, "b": 3}`
## Context

Two sub cursors (which don't share the same parent cursor), are passed to a React component as two individual `props`. I wish to update the values of both sub cursors in the same function call within that React component.

**Comment by jurassix** [comment] 2015-09-09 12:44
In older versions of Immutable you needed to actually redefine the cursor on each change.

Try something like:
```javascript
const cursor = Cursor.from(onTransaction);
function  onTransaction(newData, oldData) {
      cursor = Cursor.from(newData, onTransaction);
}
```

**Comment by jurassix** [comment] 2015-09-09 12:48
[From the source it looks like you just use `withMutations`](https://github.com/facebook/immutable-js/blob/cursor/__tests__/Cursor.ts):

```javascript
  it('can have mutations apply with a single callback', () => {
    var onChange = jest.genMockFunction();
    var data = Immutable.fromJS({'a': 1});

    var c1 = data.cursor(onChange);
    var c2 = c1.withMutations(m => m.set('b', 2).set('c', 3).set('d', 4));

    expect(c1.toObject()).toEqual({'a': 1});
    expect(c2.toObject()).toEqual({'a': 1, 'b': 2, 'c': 3, 'd': 4});
    expect(onChange.mock.calls.length).toBe(1);
  });

```

**Comment by charypar** [comment] 2015-09-09 14:02
I think the problem is more like this, in code:

```
const data = Immutable.fromJS({a: 1, b: 2});

const cursor = Cursor.from(data, newData => {
  console.log(newData)
});

const cursor1 = cursor.get('a');
const cursor2 = cursor.get('b');

// pass cursor1 and cursor2 to different places, then

cursor1.set('a', 2); // Map {"a": 2, "b": 2}
cursor2.set('b', 3); // Map {"a": 1, "b": 3}
```

The cursors are independent, changing one has no effect on the other, which makes them less useful than they could be. You could say they are not "live" - once you derive a cursor from a parent, changes to the parent (because they need to overwrite the parent), don't affect the child any more.

All the cursors do is enable you to apply "local-looking" changes to the global data structure as of the time they were created.

Normally you'd solve this with chaining, but since they are now in different places, you can't do even that. Not sure how to proceed in this case...

**Comment by charypar** [comment] 2015-09-09 14:08
The core of the problem is that each cursor holds it's own reference to the root data, not a shared one. It would IMHO require significant changes to how cursors work to enable this use-case.

**Comment by jurassix** [comment] 2015-09-09 14:41
@jameshopkins based on your requirements from _context_ section:

> Two sub cursors (which don't share the same parent cursor), are passed to a React component as two > individual props. I wish to update the values of both sub cursors in the same function call within that React component.

One approach would be to pass an `onChange` handler to the child  component that calls a function on the parent with _both_ new values. Then your parent component can use `withMutations` to make both changes transitionally.

**Comment by charypar** [comment] 2015-09-09 16:40
@jurassix that sort of defeats the point of using cursors in the first place - i.e. getting away from the callback spaghetti :)

**Comment by jurassix** [comment] 2015-09-09 17:02
Using flux, the difference between dispatching an action with a batch of updates to make to the global app state vs two sequential single updates definitely simplifies the code; which is really what I'm advocating, but my example was for the trivial non-flux case.

In practice, I think actually mutating data inside a component via `set` is something to avoid. So callbacks, or actions, that keep components _pure_ are preferred. Then when mutations are needed we dispatch actions to update our stores. A cursor then just simplifies the store and dispatching of change events.

I used to think that cursors could stand in as a replacement for flux; but because it leads to mutating global app state inside of a component I don't feel that way anymore. In non-flux apps I'd advocate for callbacks in the child components to increase the number of pure components, and reduce the actual number of components that mutate data. This separating will aid in reusability of the components outside of the current context too.

**Comment by leebyron** [comment] 2017-03-08 06:14
Closing this aging issue

**Closed by leebyron** 2017-03-08 06:14 UTC
