### ISSUE TITLE
Iterable#slice() accepts decimals

### ISSUE THREAD

**Issue by jeanlauliac** [facebook/immutable-js#638] opened 2015-09-28 10:35 UTC
Consider:

    var a = Immutable.Iterable([1,2,3])
    var b = a.slice(0, 1.5)
    console.log(b.size)
    // => 1.5

From my experience, this later causes functions like `Iterable#map` to never terminate. We probably want to enforce all containers to never ever have a decimal size, as it doesn't make sense. We can make `slice` throw on decimal indexes, or, we can mirror Array#slice behavior and just floor the passed indexes.

**Comment by rawls238** [comment] 2015-10-02 22:43
I think it makes sense to mirror the behavior of Array#slice and floor the passed indexes

**Comment by rawls238** [comment] 2015-10-02 23:17
Just tried reproducing this but was unable to, it seems like the library exhibits the proper behavior.

**Comment by leebyron** [comment] 2015-10-03 17:57
It looks like the version on the immutable website is a bit outdated, but in fact this bug has been fixed in more recent versions of Immutable.js

**Closed** 2015-10-03 17:56 UTC
