### ISSUE TITLE
Breaking change between 3.x and 4.x

### ISSUE THREAD

**Issue by richtera** [facebook/immutable-js#1504] opened 2018-04-03 13:46 UTC
### What happened
map.toArray() changed to return elements using [key, value] instead of just returning value.
```
const vals = Map({
   a: 1,
   b: 2
}).toArray();
console.log(vals);
// 3.x
[1, 2]
// 4.x
[['a', 1], ['b', 2]]
```
This causes fatal breaks in most of my react code. I think toArray should stay and maybe add a toArrayElements() or something.

**Comment by richtera** [comment] 2018-04-11 22:13
Is anyone else concerned about .toArray() working differently in the new version?

**Comment by acusti** [comment] 2018-05-03 00:58
#1340 indicates that this is likely to be a change that sticks. The justification is to more generally make the behavior of `Immutable.Map` more closely match that of native JS `Map`, where tuples are the norm for how to represent key value pairs. For example:

```js
const nativeMap = new Map([['key', 'val']]);
// Map(1) {"key" => "val"}
Array.from(nativeMap);
// [["key", "val"]]
```

From that PR, the recommended code transform is `x.toArray()` -> `x.valueSeq().toArray()` (which will be more efficient than `x.toList().toArray()`).

This is definitely a big breaking change and should be loudly called out in the final release notes for 4 stable.

**Comment by zhujinxuan** [comment] 2018-06-01 13:54
About the `toArray` in the first post, I think it is caused by the following code in `src/CollectionImpl.js`:

```
mixin(Collection, {
  // ### Conversion to other types

  toArray() {
    assertNotInfinite(this.size);
    const array = new Array(this.size || 0);
    const useTuples = isKeyed(this);
    let i = 0;
    this.__iterate((v, k) => {
      // Keyed collections produce an array of tuples.
      array[i++] = useTuples ? [k, v] : v;
    });
    return array;
  },
```

The question is that shall we fix that part of code?  Personally I think the immutable v-4's result seems more sensible. @acusti

**Comment by AnaRobynn** [comment] 2018-06-12 08:53
The change from Map.toArray => [...values] to [...[key, value]] is more familiar to how ES6 Map works and I think it's change that should stay. 

The case of changing toArray() to toList().toArray(), could be fixed via some sort of codemod?

**Comment by richtera** [comment] 2018-06-12 09:33
Sounds good. Should I close this?

**Comment by Brantron** [comment] 2018-06-14 16:59
@richtera yes, please close this

**Closed** 2018-06-14 18:40 UTC
