### ISSUE TITLE
Record flow implementation

### ISSUE THREAD

**Issue by NullDivision** [facebook/immutable-js#1154] opened 2017-03-12 23:47 UTC
After the refactoring, extended records don't work anymore. I get the error `Expected polymorphic type instead of class type: Record.`.

Flow definition files don't help either.

Looking at the type-def tests it would seem that the only test covering extended records is:

```
class ABClass extends (Record({a:1, b:2}): any) {
  setA(a: number) {
    return this.set('a', a);
  }

  setB(b: number) {
    return this.set('b', b);
  }
```

This doesn't seem right. We should be able to define set properties with something like v3:

```
declare class extends Record<{ a: number, b: ?string }>
```

**Comment by leebyron** [comment] 2017-03-13 00:07
Unfortunately in the previous version the any was *implicit*, so no type checking was occurring at all for Records. In v4 extending Records in a class requires an explicit cast.

I spent some time trying to get Records as soundly typed as possible, but would appreciate help from anyone who can find a way to support this case

**Comment by alexfedoseev** [comment] 2017-03-13 07:42
> Unfortunately in the previous version the any was implicit, so no type checking was occurring at all for Records

I might misunderstand something, but extended records seem to work in v3: https://cl.ly/jXBT

**Comment by NullDivision** [comment] 2017-03-13 08:51
So, I've managed to (partly) fix the issue of type-defs by adding a `T` to Record like so:

```
declare class Record<T> {
  static (spec: T, name?: string): RecordClass<T>;
  constructor(spec: Values, name?: string): RecordClass<T>;

  static isRecord: typeof isRecord;

  static getDescriptiveName(record: RecordInstance<*>): string;
}
```

The only issue now is that implementations don't see the `get()` method.

**Comment by alexfedoseev** [comment] 2017-03-13 11:11
I just bumped immutable on the main project and I receive these errors on non-extended records, e.g.: 

https://cl.ly/jXHq

```
constructor call: .../state.js:19
Constructor cannot be called on RecordClass: .../state.js:19

type application of identifier `Record`: .../storeDataSelector.js:9
Expected polymorphic type instead of class type: Record: .../state.js:10
```



Those are all over the code base.

**Comment by gajus** [comment] 2017-03-14 19:19
> So, I've managed to (partly) fix the issue of type-defs by adding a T to Record like so:

You said partially. Whats the downside to this?

**Comment by NullDivision** [comment] 2017-03-14 20:25
Extended records have some issues.

* subset functions of Iterable (eg. equals, has, etc) aren't visible to Flow (guessing it's an issue with the RecordClass definition)
* and in some cases when I use it in my React props it tells me to use typeof

Feel free to copy-paste it into immutable.js.flow and check it out. I'd love to find out why.

**Comment by NullDivision** [comment] 2017-03-16 07:43
That's because you're essentially telling the inference engine that the result of your class is a RecordInstance instead of ABClass i think.

**Comment by philipp-spiess** [comment] 2017-03-16 08:14
@NullDivision I think flow is well aware of the ABClass  type since all tests with 't1' work as expected (even the first call auf 'setA') The problem is that methods like 'set' create a new record instance which flow does not recognize as ABClass but only as RecordInstance (the place where 'set' is defined)

I struggled with your ideas because  it appears that the newest version of flow only let you extend from "polymorphic types". That's why my approach required 'Class<>'

**Comment by NullDivision** [comment] 2017-03-16 08:31
`React.Component<DefaultProps, Props, State>` seems to work perfectly fine on Flow v0.41.0 so I'm not really sure what you mean by only allowing extension on polymorphic types.

What if you try a signature of:

`class ABClass extends (Record({a: 1, b: 2})<{a: number, b: number}>)`

**Comment by johnfn** [comment] 2017-03-16 08:34
I was able to get an explicitly typed version of Records working with TypeScript here: https://github.com/facebook/immutable-js/issues/1172#issuecomment-286985608

**Comment by NullDivision** [comment] 2017-03-16 08:40
I'm not sure what to make of your TS definition but I wish you'd have used Record instead of MakeRecord. :D

However a takeaway that I see is that the use of Record, RecordClass and RecordInstance is kind of an overkill. What about merging RecordClass into RecordInstance?

**Comment by johnfn** [comment] 2017-03-16 08:48
You could modify it to use Record instead, if you'd like! 😄

**Comment by philipp-spiess** [comment] 2017-03-16 09:21
@NullDivision when I try your addition to the `Record` type in the test file that is part of the repository:

```
record.js:41
 41: class ABClass extends Record({a: 1, b: 2})<DefaultProps> {
           ^^^^^^^ ABClass. Expected polymorphic type instead of
 41: class ABClass extends Record({a: 1, b: 2})<DefaultProps> {
                           ^^^^^^^^^^^^^^^^^^^^ RecordClass

record.js:41
 41: class ABClass extends Record({a: 1, b: 2})<DefaultProps> {
                           ^^^^^^^^^^^^^^^^^^^^ statics of this instantiation of function call. Expected polymorphic type instead of
 41: class ABClass extends Record({a: 1, b: 2})<DefaultProps> {
                           ^^^^^^^^^^^^^^^^^^^^ RecordClass

record.js:43
 43:     return this.set('a', a);
                ^^^^^^^^ property `set`. Expected polymorphic type instead of
 41: class ABClass extends Record({a: 1, b: 2})<DefaultProps> {
                           ^^^^^^^^^^^^^^^^^^^^ RecordClass

record.js:47
 47:     return this.set('b', b);
                ^^^^^^^^ property `set`. Expected polymorphic type instead of
 41: class ABClass extends Record({a: 1, b: 2})<DefaultProps> {
                           ^^^^^^^^^^^^^^^^^^^^ RecordClass

record.js:51
 51: var t1 = new ABClass({a: 1});
                  ^^^^^^^ constructor return. Expected polymorphic type instead of
 41: class ABClass extends Record({a: 1, b: 2})<DefaultProps> {
                           ^^^^^^^^^^^^^^^^^^^^ RecordClass

record.js:54
 54: // $ExpectError
     ^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

record.js:58
 58: // $ExpectError
     ^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

record.js:60
 60: // $ExpectError
     ^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression


Found 8 errors

````

I'm running flow `0.41.0`

**Comment by hannupekka** [comment] 2017-05-27 19:49
Getting the same error when trying to describe my Redux state as a Record:
```
type State = Record<{
  isLoading: boolean
}>;

const state: State = Record({
  isLoading: false
});

// -> RecordClass. Expected polymorphic type instead of class type: Record
```

**Comment by TomiS** [comment] 2017-06-28 22:43
I'm also getting same `Expected polymorphic type instead of class type: Record` when using `4.0.0-rc.2`. However, after reading pretty much all related tickets I'm still not sure whether I'm using the Record typings correctly.

I created a quick modification to tests to illustrate what I'm trying to do. I would expect those tests to run and all getters in `record-imports.js` to be covered by flow but they are not.

https://github.com/TomiS/immutable-js/commit/ff3233ab274c76d8282c87bb527d02ba39c36ecb

Is this even nearly correct? (sorry about a few extra spaces in diff caused by prettier)

**Comment by dperetti** [comment] 2017-07-16 10:44
We have a showstopper, here, it's no minor issue. And it has been many months now.
Flow: Facebook.
Immutable: Facebook.
How come it has not been solved yet ?
Sorry for the gripe, but it had to be said.

**Comment by TomiS** [comment] 2017-07-17 09:35
I agree this is an issue that severely weakens the usefulness of Flow for everyone using Immutable.js. I also understand this might be very difficult to solve because it requires deep understanding of both Immutable.js and Flow. The question is if there is a person with such knowledge within community who could help (I'm afraid I don't have the required skills yet) or does this require the golden touch of good ppl at FB?

**Comment by dperetti** [comment] 2017-07-17 09:48
To be honest, I think is pretty much a dead end.
Not blaming FB people here: it's just we all want to achieve on top of Immutable something that might be too complicated for a javascript type checker.
But there is good news. I've stumbled upon a fantastic library that IMHO deserves some light.
Please have a look:
https://github.com/pbomb/flow-immutable-models
This is, as far as I'm concerned, exactly what I need.
You get models (backed by Immutable) that Flow (and IDEs!) can easily understand, even with nested structures. No hack, no tortuous type definitions. It's brillant. Please share !

**Comment by leebyron** [comment] 2017-10-04 01:49
Closing this issue since the latest RC has dramatically better flow types for Records, especially with the new `RecordOf<T>` flow type.

**Closed by leebyron** 2017-10-04 01:49 UTC
Labels: enhancement, help wanted

**Comment by schovi** [comment] 2018-06-28 13:31
@leebyron Hello. You mention `RecordOf()` which seems like solution for our problem, but I can't find out how to arrange that together. We are trying to add flow types to Slate editor.

Given the source of class `class Value extends Record(DEFAULTS) { ... }` where DEFAULTS is some shape.
https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/models/value.js#L34

We are experimenting to declare class types as:

```javascript
declare export class Value extends Record<{
  data: Map,
  decorations: ToBeDefined,
  document: Document,
  history: History,
  schema: Schema,
  selection: Range
}> {
  static fromJSON(json: Value | Object): Value
  ...
}
```

This is one valid syntax which Flow allow us, but any checking of Record properties, or functions doesn't work.
Is it even possible to inherit from this kind of Generic?
